const STAT_HP_MAX = "hp_max";
const STAT_MP_MAX = "mp_max";
const STAT_HP_ENDURANCE = "hp_end";
const STAT_MP_ENDURANCE = "mp_end";
const STAT_MARTIAL_OFFENSE = "mar_atk";
const STAT_MARTIAL_DEFENSE = "mar_def";
const STAT_PSIONIC_OFFENSE = "psi_atk";
const STAT_PSIONIC_DEFENSE = "psi_def";
const STAT_ARCANE_OFFENSE = "arc_atk";
const STAT_ARCANE_DEFENSE = "arc_def";

const STAT_LIST = [
	STAT_HP_MAX,
	STAT_MP_MAX,
	STAT_HP_ENDURANCE,
	STAT_MP_ENDURANCE,
	STAT_MARTIAL_OFFENSE,
	STAT_MARTIAL_DEFENSE,
	STAT_PSIONIC_OFFENSE,
	STAT_PSIONIC_DEFENSE,
	STAT_ARCANE_OFFENSE,
	STAT_ARCANE_DEFENSE,
]

const LEVEL_STAT_LIST = [
	STAT_HP_ENDURANCE,
	STAT_MP_ENDURANCE,
	STAT_MARTIAL_OFFENSE,
	STAT_MARTIAL_DEFENSE,
	STAT_PSIONIC_OFFENSE,
	STAT_PSIONIC_DEFENSE,
	STAT_ARCANE_OFFENSE,
	STAT_ARCANE_DEFENSE,
]

const AVG_STAT_PER_LEVEL = 10;

/*
CORE STATS : given only by levels
EQUIP STATS : given by equips
SKILL BONUS : given by skills
*/