SCENES.opening_arrive = {
	log : [
		{text:"You arrive at Asolaz and step onto the campus for the first time.", location:"quad"},
		{speaker:"Ammette", text:"Hello, [pname]. Welcome to Asolaz.", charimg:{character:"ammette", outfit:"default", pose:"standing"}},
		{speaker:"Ammette", text:"I'm Ammette, the registrar and also ostensibly the academic advisor because the management here apparently doesn't know the difference between a registrar and an academic advisor."},
		{speaker:"Ammette", text:"But I digress. Time for the spiel."},
		{speaker:"Ammette", text:"Here at Asolaz, we believe that the best way for our students to learn is to turn them loose and let them do whatever until they literally magically become better."},
		{speaker:"Ammette", text:"Apparently it just works sometimes because we've produced some of the finest mages who have ever lived, most notably both Fremdl and Psinnit."},
		{speaker:"Ammette", text:"Now let me lay down the rules and expectations for you."},
		{speaker:"Ammette", text:"Asolaz is in international waters, so we have our own set of laws."},
		{speaker:"Ammette", text:"Don't steal anything. Don't assault anyone. And don't commit any international war crimes. Those are our laws."},
		//{speaker:"Ammette", text:"I think it has to do with an NAP or something? I don't know politics."},
		{speaker:"Ammette", text:"We also have school rules, which are less important and mostly for your own safety."},
		{speaker:"Ammette", text:"Don't pick fights unless you have a combat license, don't enter labyrinths unless you have a combat license and a labyrinth license and a safety harness."},
		{speaker:"Ammette", text:"We also have some recommendations for your own health."},
		{speaker:"Ammette", text:"Like, please, go to sleep about once a day. If you don't, you will accumulate pstrez until you start convulsing on the floor, and that's not fun. Trust me."},
		{speaker:"Ammette", text:"Let me show you around. Follow me."},
		{speaker:"Ammette", text:"This is where the offices are, including mine. If you want to register for classes, licenses, exams, or tournaments, you come right here.", location:"bureau"},
		{speaker:"Ammette", text:"This is the clinic. We take you here if you get almost killed in a labyrinth, you come down with a disease, or you build up too much pstrez and start convulsing on the floor.", location:"clinic"},
		{speaker:"Ammette", text:"This is the tailory. You can improve your clothing here. Useful if for some reason you don't want to get almost killed in a labyrinth and end up in the aforementioned clinic.", location:"tailory"},
		{speaker:"Ammette", text:"This is the library, where you can read books, as one might come to expect of a library.", location:"library"},
		{speaker:"Ammette", text:"This is the arena. If you want to train in combat, or spar with other people, you can do so here, but first you'll need a combat license.", location:"arena"},
		{speaker:"Ammette", text:"I think the next combat license test is tomorrow."},
		//{speaker:"Ammette", text:"This is a labyrinth. It's a weird semi-illusory place made by weird archaea.", location:"library"},
		{speaker:"Ammette", text:"I have the rest of the day off. Tommorrow, you can come see me at the Bureau and get registered for something. Or don't.", location:"dorms"},
		{speaker:"Ammette", text:"Until then, you can just wander around the campus and meet some people or read some books or something."},
		{speaker:"Ammette", text:"Here, this is your room. It has a bed and a personal computer and some other things. Bye, see you later."},
		{action:"return"},
	]
}